### ISSUE TITLE
RequestOptions.extract has wrong function type.

### ISSUE THREAD

**Issue by bduisenov** [spacejack/mithril.d.ts#11]
Hi, @spacejack 

In mithril.d.ts#1.0.2 `RequestOptions.extract` has function which return type seems to be not correct:
`extract?: (xhr: XMLHttpRequest, options: RequestOptions<T>) => string;`

according to mithril's documentation example it can be not only a `string` but an object as well:
`extract: function(xhr) {return {status: xhr.status, body: xhr.responseText}}`

Cheers,
Babur

**Comment by spacejack** [comment]
Doing some additional testing with mithril's request API, it looks like it follows these rules:

If you provide a `deserialize` callback, you will get the `xhr.responseText` string and can deserialize it manually.

If you provide an `extract` callback, you get the XHR object and can do whatever with that. As you say, mithril will not attempt to deserialize the result of that callback.

If you provide extract, then only extract will be used and deserialize will be skipped whether you provide it or not.

So I think this means we can type the result of both deserialize and extract as `T` rather than any. (If you want `any` then you can do `m.request<any>(...`

**Comment by spacejack** [comment]
Here's [a jsbin](https://jsbin.com/pidebukoko/edit?js,console,output) if you want to experiment.

**Comment by spacejack** [comment]
I've pushed up fixes for this.

**Comment by bduisenov** [comment]
cool @spacejack, thanks.
